name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt
      - name: Build
        run: cargo build --manifest-path logoscope/Cargo.toml --locked --all-targets
      - name: Test
        run: cargo test --manifest-path logoscope/Cargo.toml --locked --all
      - name: Lint (Clippy)
        run: cargo clippy --manifest-path logoscope/Cargo.toml -- -D warnings
      - name: Format check
        run: cargo fmt --manifest-path logoscope/Cargo.toml --all -- --check

