name: npm-publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish @logoscope/cli to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Verify npm package version matches tag
        working-directory: npm
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          echo "Tag: $TAG_NAME"
          PKG_VERSION=$(node -p "require('./package.json').version")
          echo "Package version: v$PKG_VERSION"
          if [[ "v$PKG_VERSION" != "$TAG_NAME" ]]; then
            echo "Version mismatch: package.json ($PKG_VERSION) != tag ($TAG_NAME)" >&2
            exit 1
          fi

      - name: Install dependencies
        working-directory: npm
        run: npm install --no-audit --no-fund

      - name: Publish to npm
        working-directory: npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public

